### ISSUE TITLE
tunnel -- panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by hh** [coder/wgtunnel#18]
```
go install github.com/coder/wgtunnel/cmd/tunnel
```

```
~/go/bin/tunnel -api-url https://try.ii.nz --wireguard-key `wg genkey` localhost:8030
panic: non-positive interval for NewTicker

goroutine 36 [running]:
time.NewTicker(0x140000684b8?)
	/opt/homebrew/Cellar/go/1.20.2/libexec/src/time/tick.go:24 +0x110
github.com/coder/wgtunnel/tunnelsdk.(*Client).LaunchTunnel.func2()
	/Users/hh/src/wgtunnel/tunnelsdk/tunnel.go:232 +0x58
created by github.com/coder/wgtunnel/tunnelsdk.(*Client).LaunchTunnel
	/Users/hh/src/wgtunnel/tunnelsdk/tunnel.go:231 +0x738
```

**Comment by hh** [comment]
This was caused by a new version of the client connecting to an old version of the server.
Once they were both running the same version, the error went away.

I suspect the API changed.
